# Generated by Django 5.2.4 on 2025-07-07 05:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.IntegerField()),
                ('taskTitle', models.CharField(max_length=200)),
                ('taskDesc', models.CharField(max_length=500)),
                ('taksTime', models.DateTimeField(default=datetime.datetime.now)),
                ('taskStat', models.BooleanField(default=0)),
                ('taskUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
